### ISSUE TITLE
Enable cherry-picker for the repository

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes-sigs/cluster-api-operator#123]
**User Story**

As a maintainer of the repo, in the future maintainers might want to backport some PRs' (bug fixes, documentation etc) to stable branches (i.e from main => release-0.1/0.2). To do that, we could make use k8s community provided [cherry-picker](https://docs.prow.k8s.io/docs/components/external-plugins/cherrypicker/) which can take care of it for us easily.

**Detailed Description**

Example usage command, which can be commented on the PR targeting the `main` branch and cherry-picking of the PR is requested to `release-0.2` branch:

```
/cherrypick release-0.2
```

Once PR targeting the `main` branch is merged, k8s cherry-pick bot should open a PR automatically towards the targeted branch and assign the commenter on the PR

**Anything else you would like to add:**
We need a PR in https://github.com/kubernetes/test-infra to enable it and I can work on it

[Miscellaneous information that will assist in solving the issue.]

/kind feature
/area ci

**Comment by alexander-demicev** [comment]
sounds good to mee
