### ISSUE TITLE
Support clusterctl upgrade plan

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-operator#129]
**User Story**

As a user/operator I would like to determine the current CAPI* versions being used on the management cluster as well as if there is an upgrade available using `clusterctl upgrade plan` so that I don't have to take as long to manually figure this out probing deployments or other manual means.

**Detailed Description**
Only support `clusterctl upgrade plan` to determine current and upgradeable versions for the mangement cluster.  `clusterctl upgrade apply` out of scope for this feature request.  Currently if you run this against a cluster which has CAPI and the provider installed, you get this:

```
Checking new release availability...
Error: invalid management cluster: there should a core provider, found 0
```

/kind feature

**Comment by alexander-demicev** [comment]
@dtzar This can be achieved by writing a plugin for `clusterctl` that can work with operator API https://github.com/kubernetes-sigs/cluster-api/pull/8957
