### ISSUE TITLE
Cluster API operator missing from sigs.yaml

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api-operator#17]
It seems the project info are missing from https://github.com/kubernetes/community/blob/master/sigs.yaml. Please file a PR to k/community

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]

**Comment by neolit123** [comment]
looks like created a duplicate issue:
https://github.com/kubernetes-sigs/cluster-api-operator/issues/22

> we are currently doing some cleanup in our portion of the sigs.yaml, but once this PR merges you can follow the existing YAML structure to PR this project in the sigs.yaml:
kubernetes/community#6402

please hold until that PR merges to avoid conflicts.
