### ISSUE TITLE
Helm chart support for overriding images and image pull secrets

### ISSUE THREAD

**Issue by adriananeci** [kubernetes-sigs/cluster-api-operator#171]
**User Story**

As a cluster fleet operator I would like to be able to use images from private registries in order to deploy the CAPI operator in an air gapped environment.

**Detailed Description**

In order to be able to allow a fully air gapped installation, the CAPI Operator helm chart should expose ways to override the images and image pull secrets used in the controller manager deployment at a minimum.

**Anything else you would like to add:**

Not sure if it is already tracked in https://github.com/kubernetes-sigs/cluster-api-operator/issues/130

/kind feature

**Comment by alexander-demicev** [comment]
@adriananeci This change will be included in one the next releases

**Comment by Fedosin** [comment]
/assign

I started working on this
