### ISSUE TITLE
Cannot add infrastructure provider after the initial installation

### ISSUE THREAD

**Issue by cwrau** [kubernetes-sigs/cluster-api-operator#283]
**What steps did you take and what happened:**
I tried adding an infrastructure provider during an upgrade, which didn't work because they are installed via `post-install` hooks, which of course don't trigger during any phase of an upgrade.

**What did you expect to happen:**
That the corresponding resources are just created like any other normal resource instead of with some kind of hook.
In the short term that the `post-upgrade` hook be added as well.

**Anything else you would like to add:**
The root cause for this problem is that the CRDs aren't inside the `crds` folder, which I addressed in https://github.com/kubernetes-sigs/cluster-api-operator/issues/282

**Environment:**

- Cluster-api-operator version: N/A
- Cluster-api version: N/A
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A
- Helm Chart version: 0.6.0

/kind bug

**Comment by alexander-demicev** [comment]
There is a limitation on Helm side for upgrades, we can't place CRDs in `crds` directory and Helm doesn't wait for CRDs to be registered on the upgrade(this seems to be intended). We have an issue https://github.com/kubernetes-sigs/cluster-api-operator/issues/188 that suggests how upgrades can be fixed but currently, we only support installing providers on `helm install` command.

**Comment by cwrau** [comment]
> we can't place CRDs in `crds` directory

Why not? 🤔

I understand, see [*duplicated explanation*](https://github.com/cert-manager/cert-manager/issues/6179#issuecomment-1764051690)

**Comment by cwrau** [comment]
> > we can't place CRDs in `crds` directory
> 
> Why not? 🤔
> 
> See [_duplicated explanation_](https://github.com/cert-manager/cert-manager/issues/6179#issuecomment-1764051690)

This is still needed
