### ISSUE TITLE
Update CAPI secret mechanism to supported method

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-operator#287]
**User Story**

As a developer/user/operator I would like to ensure that the secret authentication method for CAPI is utilizing the current supported method.

**Detailed Description**
The current method the operator helm chart uses to install is [the deprecated use of environment variables](https://capz.sigs.k8s.io/topics/getting-started#warning-1).

1. clusterctl init
2. create k8s secret with creds
3. refer to the secret via AzureClusterIdentity ref in AzureCluster 

Is the current supported way to authenticate and should be reflected by default in the installation process.

/kind feature

**Comment by alexander-demicev** [comment]
@dtzar I followed [CAPI quickstart](https://cluster-api.sigs.k8s.io/user/quick-start.html#initialization-for-common-providers) guide and was able to deploy CAPZ with the operator. I think it should be good from the operator side, what users have to do is:

1. Deploy operator with CAPZ as infra provider, no credentials secret required for it.
2. Create a k8s secret to be used with AzureClusterIdentity.
3. Create AzureClusterIdentity.
4. Create AzureClusters that reference it.
