### ISSUE TITLE
Official abbreviation for cluster api operator

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/cluster-api-operator#357]
**User Story**

As a lazy human, I want to avoid to type "cluster api operator".

An official abbreviation [glossary](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/reference/glossary.md) would be nice.

/kind feature

**Comment by kranurag7** [comment]
I think we can use `CAO` and IMHO it'll not be a naming conflict with downstream CAPI providers as per the naming contract of cluster-api. 
Ref: https://cluster-api.sigs.k8s.io/developer/providers/implementers-guide/naming#repository-naming

**Comment by Fedosin** [comment]
Done by https://github.com/kubernetes-sigs/cluster-api/pull/10005
