### ISSUE TITLE
Support short Names for capi-operator objects 

### ISSUE THREAD

**Issue by kranurag7** [kubernetes-sigs/cluster-api-operator#361]
**User Story**

As an operator, I want to use shortNames while managing cluster-api-operator objects in the cluster. As of now, we don't support any shortnames for any of our custom resources. Given the names are large, it will be great if we add short names. 

```bash
NAME                      SHORTNAMES   APIVERSION                           NAMESPACED   KIND
addonproviders                         operator.cluster.x-k8s.io/v1alpha2   true         AddonProvider
bootstrapproviders                     operator.cluster.x-k8s.io/v1alpha2   true         BootstrapProvider
controlplaneproviders                  operator.cluster.x-k8s.io/v1alpha2   true         ControlPlaneProvider
coreproviders                          operator.cluster.x-k8s.io/v1alpha2   true         CoreProvider
infrastructureproviders                operator.cluster.x-k8s.io/v1alpha2   true         InfrastructureProvider
```

**Detailed Description**

I think we can use `p` for provider given it's common in all along with type of provider in the prefix. For example, something like `addonp` for `addonprovider` and `infrap` for `infraprovider` but even after reduction this sounds a little big. :)
I'm open to more thoughts here. 

**Anything else you would like to add:**

Happy to work on this once we finalize on the naming convention. 

/kind feature

**Comment by Fedosin** [comment]
@kranurag7 oh... I didn't realize that you've already taken this task.
