### ISSUE TITLE
`featureGate` adds the `--feature-gates` arg on all deployments and break Azure Service Operator deployed alongside CAPZ

### ISSUE THREAD

**Issue by synthe102** [kubernetes-sigs/cluster-api-operator#388]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

When setting `specs.manager.featureGates`, deployments other than the manager gets patched with the `--feature-gates` flag.
For instance CAPZ deploys Azure Service Operator, which breaks when using `featureGates` because the `--feature-gates` flag is added to the deployment args.

**What did you expect to happen:**
`featureGates` should only patch the manager deployment.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-operator version: v0.7
- Cluster-api version: 1.5.3
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): 1.24
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]

**Comment by synthe102** [comment]
@Fedosin thanks a lot for fixing this so fast. Could it be possible to have a 0.8.1 release to include this patch ?

**Comment by Fedosin** [comment]
@synthe102 hey, np :) thank you for reporting the bug. I've already proposed a backport: https://github.com/kubernetes-sigs/cluster-api-operator/pull/391
