### ISSUE TITLE
Chart Installation Not Working

### ISSUE THREAD

**Issue by putnam120** [kubernetes-sigs/cluster-api-operator#389]
**What steps did you take and what happened:**
1. Added and updated the helm repo with `helm repo add capi-operator https://kubernetes-sigs.github.io/cluster-api-operator; helm repo update`.
2. Attempt to install via `helm install capi-operator capi-operator/cluster-api-operator --create-namespace -n capi-operator-system --set infrastructure=vcluster  --set logLevel=10 --wait`

However, I end up with the following error message
```
Error: INSTALLATION FAILED: timed out waiting for the condition
```

**What did you expect to happen:**
I expected the cluster api operator to have been successfully installed within my cluster.

**Anything else you would like to add:**
I am using a local kubernetes cluster created with K3D. The cluster was created with `k3d cluster create test`.

**Environment:**

- Cluster-api-operator version: 0.8.0
- Cluster-api version:
- Minikube/KIND version: k3d version v5.6.0 with k3s version v1.27.4-k3s1 (default)
- Kubernetes version: (use `kubectl version`): 1.27.4
- OS (e.g. from `/etc/os-release`): MacOS

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]

**Comment by alexander-demicev** [comment]
This is happening when cert-manager is not installed, this can be done manually by user with any preferred way or by using CAPI operator chart https://github.com/kubernetes-sigs/cluster-api-operator/tree/main/docs#installing-cert-manager-using-helm-chart
