### ISSUE TITLE
rate limit for github api has been reached

### ISSUE THREAD

**Issue by guettli** [kubernetes-sigs/cluster-api-operator#394]
**What steps did you take and what happened:**

I tried to use CAPIO and I get this condition:

```
resource: coreproviders 
name: cluster-api
Condition ProviderInstalled=False ComponentsFetchError "failed to read \"\" from the repository for provider \"cluster-api\": failed to get GitHub release v1.6.0: rate limit for github api has been reached. Please wait one hour or get a personal API token and assign it to the GITHUB_TOKEN environment variable"
```

I added the env var GITHUB_TOKEN to the capio deployment, but this seems to be ignored.

There are some docs about github-token [here](https://github.com/kubernetes-sigs/cluster-api-operator/tree/main/docs#installing-azure-infrastructure-provider), but they describe only how to provide the token for the infra-provider.

Please tell me (and in the README) how to provide the github-token to capio.

Thank you very much.

- Cluster-api-operator version: 0.7
- Cluster-api version: 1.6.0
- Kubernetes version: (use `kubectl version`): 1.28
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]

**Comment by alexander-demicev** [comment]
Github token can be added to the provider secret, it's documented here https://github.com/kubernetes-sigs/cluster-api-operator/tree/main/docs#installing-azure-infrastructure-provider. I guess we need to highlight it better.
