### ISSUE TITLE
Can't install an infrastructure provider if the github tag for a release exists but the release doesn't.

### ISSUE THREAD

**Issue by nat-henderson** [kubernetes-sigs/cluster-api-operator#464]
**What steps did you take and what happened:**

At time of writing, CAPA v2.4.1 has an extant tag, but not an extant release.  According to the folks over at CAPA, this is normal for them, and it usually takes about half an hour from tag creation to release creation.

<img width="1128" alt="Screenshot 2024-03-18 at 10 35 29 AM" src="https://github.com/kubernetes-sigs/cluster-api-operator/assets/605324/0853cb91-39f5-48fb-ac42-038a215481da">
<img width="1153" alt="Screenshot 2024-03-18 at 10 35 36 AM" src="https://github.com/kubernetes-sigs/cluster-api-operator/assets/605324/48d1dd24-4ed5-4eb8-887a-72b9db4a5f76">

I attempted to install the AWS provider in my cluster (in an integration test, using a config which has worked before).  To emphasize - I am _not_ attempting to use the new, incomplete release, I am attempting to use the previous release.

Unfortunately, the provider was not installed, and here are the relevant portions of the logs:

```
I0318 17:36:12.526031       1 preflight_checks.go:57]  "msg"="Performing preflight checks" "InfrastructureProvider"={"name":"aws","namespace":"default"} "controller"="infrastructureprovider" "controllerGroup"="operator.cluster.x-k8s.io" "controllerKind"="InfrastructureProvider" "name"="aws" "namespace"="default" "reconcileID"="9cc1b9c1-337e-49eb-ad3c-8eca3bca8fa9"
I0318 17:36:12.536389       1 preflight_checks.go:206]  "msg"="Preflight checks passed" "InfrastructureProvider"={"name":"aws","namespace":"default"} "controller"="infrastructureprovider" "controllerGroup"="operator.cluster.x-k8s.io" "controllerKind"="InfrastructureProvider" "name"="aws" "namespace"="default" "reconcileID"="9cc1b9c1-337e-49eb-ad3c-8eca3bca8fa9"
I0318 17:36:12.990526       1 manifests_downloader.go:77]  "msg"="Downloading provider manifests" "InfrastructureProvider"={"name":"aws","namespace":"default"} "controller"="infrastructureprovider" "controllerGroup"="operator.cluster.x-k8s.io" "controllerKind"="InfrastructureProvider" "name"="aws" "namespace"="default" "reconcileID"="9cc1b9c1-337e-49eb-ad3c-8eca3bca8fa9"
E0318 17:37:13.260243       1 controller.go:329]  "msg"="Reconciler error" "error"="failed to create repo from provider url for provider \"aws\": error creating the GitHub repository client: failed to get latest release: release not found for version v2.4.1, please retry later or set \"GOPROXY=off\" to get the current stable release: 404 Not Found" "InfrastructureProvider"={"name":"aws","namespace":"default"} "controller"="infrastructureprovider" "controllerGroup"="operator.cluster.x-k8s.io" "controllerKind"="InfrastructureProvider" "name"="aws" "namespace"="default" "reconcileID"="9cc1b9c1-337e-49eb-ad3c-8eca3bca8fa9"
```

**What did you expect to happen:**

I expected the provider to be installed despite CAPA's in-progress release.

**Environment:**

- Cluster-api-operator version: 0.8.1
- Cluster-api version: 1.6.2
- Kubernetes version: (use `kubectl version`): 1.27.3

/kind bug

**Comment by furkatgofurov7** [comment]
/triage accepted

@nat-henderson hey, this is a well known issue and the bug is not in the Cluster API Operator but rather in Cluster API. There is already PR to fix it in CAPI: https://github.com/kubernetes-sigs/cluster-api/pull/10220 however it is under review. 

In such situations, where tag is there but not release yet, the only option until above fix is merged is wait for the release with that tag tp be published. And usually, providers try to cut the time between tag pushing and cutting a release as short as possible due to this issue. Looks like CAPA has [v2.4.1 ](https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v2.4.1) published bit after this issue was created, so you can try again 🙂

**Comment by nat-henderson** [comment]
Acknowledged; thanks; I thought I'd found the code that was at fault but not the PR addressing it; thanks for the link!  Will follow that PR.
