### ISSUE TITLE
Cluster API operator is not accepting internal repository fetchconfig url 

### ISSUE THREAD

**Issue by rajgani** [kubernetes-sigs/cluster-api-operator#488]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
Cluster API operator is not accepting internal repository fetchconfig url  

* Deploy Cluster API Operator
* Try to apply Core Provider Custom Resource

```apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-system
spec:
  fetchConfig:
    url: https://example.com/stash/projects/E-C/repos/cluster-api/browse/core-components.yaml?at=development
```
**What did you expect to happen:**
We are trying to deploy Cluster API operator in an AirGap environment which do not have access to Github.com or Gitlab.com, we see Cluster API Operator supports Airgap installations, however while deploying CoreProvider in capi-system namespace with an Internal repository url, it throws below error.

`E0410 17:49:52.667842       1 controller.go:329]  "msg"="Reconciler error" "error"="failed to create repo from provider url for provider \"cluster-api\": invalid provider url. Only GitHub and GitLab are supported for \"https\" schema" "CoreProvider"={"name":"cluster-api","namespace":"capi-system"} "controller"="coreprovider" "controllerGroup"="operator.cluster.x-k8s.io" "controllerKind"="CoreProvider" "name"="cluster-api" "namespace"="capi-system" "reconcileID"="e2a00b85-08ce-4796-854e-486c106519eb"`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-operator version: v0.9.1
- Cluster-api version: v1.6.3
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`): v1.24.17
- OS (e.g. from `/etc/os-release`): CentOS 7.9

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]

**Comment by furkatgofurov7** [comment]
@rajgani hey. 

Have you tried using ConfigMap instead of specifying url: `spec.fetchConfig.selector.matchLabels.provider-components`
described in https://cluster-api-operator.sigs.k8s.io/03_topics/02_configuration/01_air-gapped-environtment.html#air-gapped-environment and that helps?
