### ISSUE TITLE
Secret "capi-operator-webhook-service-cert" is not automatically created

### ISSUE THREAD

**Issue by henrypham67** [kubernetes-sigs/cluster-api-operator#520]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
I followed the [Quick Start Operator](https://cluster-api.sigs.k8s.io/user/quick-start-operator) and got the `secret "capi-operator-webhook-service-cert" not found` error from pod of `capi-operator-cluster-api-operator` deployment

**What did you expect to happen:**
The operator chart should be installed successfully

**Environment:**

- Cluster-api-operator version: 0.10.1
- Cluster-api version: N/A
- Minikube/KIND version: v0.22.0 go1.20.13 linux/amd64
- Kubernetes version: (use `kubectl version`): v1.29.2
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.4 LTS

/kind bug

**Comment by mxmxchere** [comment]
Hi @henrypham67 you said that you deployed like it was described in the quickstart guide. I assume that you deployed cert-manager with the capi-operator. Maybe this is a timing issue that you can fix by deploying cert-manager manually upfront (for test) `kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.yaml`. Then wait for all cert-manager pods to be ready and afterwards deploy the cluster-api-operator chart with `helm install capi-operator capi-operator/cluster-api-operator --create-namespace -n capi-operator-system --set infrastructure=docker --set cert-manager.enabled=false --set configSecret.name=${CREDENTIALS_SECRET_NAME} --set configSecret.namespace=${CREDENTIALS_SECRET_NAMESPACE}  --wait --timeout 90s
`
The important part here is that i disabled the cert-manager chart with `--set cert-manager.enabled=false`

**Comment by dat-cao-tien** [comment]
Hi @mxmxchere, thank you for your response but after giving it a try I still hit the same issue
<script src="https://gist.github.com/dat-cao-tien/cd5c9d3ba18dabd0ee15793965df06a1.js"></script>

**Comment by henrypham67** [comment]
Hi @mxmxchere, thank you for your response. I gave it a try and am still getting the same issue
https://gist.github.com/henrypham67/ae673f09fa4864352bb29cb53f89774c

**Comment by henrypham67** [comment]
Hi @mxmxchere thank you for your response, I gave it a try and am still getting the issue
https://gist.github.com/henrypham67/b353c5a3c940696428e3d4a4345deb81

**Comment by mxmxchere** [comment]
okay, the missing secret should be generated by the cert-manager. I think you have to find out what is stuck there. You can start to look for errors by inspecting the cert resource

`k describe -n capi-operator-system certificate capi-operator-serving-cert`

**Comment by dat-cao-tien** [comment]
It's weird because I can not find any certificates in all namespace using `kubectl get certificate -A`

**Comment by henrypham67** [comment]
It's weird because I can not find any certificate using the command `kubectl get certificate -A`

**Comment by mxmxchere** [comment]
Ok, as far as i can see the cert is defined in the file `operator-components.yaml` i was not able to find it in the repo, but it is in the release in the helmrepo. Maybe you can try:

`helm install capi-operator https://github.com/kubernetes-sigs/cluster-api-operator/releases/download/v0.10.1/cluster-api-operator-0.10.1.tgz
 --create-namespace -n capi-operator-system --set infrastructure=docker --set cert-manager.enabled=false --set configSecret.name=${CREDENTIALS_SECRET_NAME} --set configSecret.namespace=${CREDENTIALS_SECRET_NAMESPACE}  --wait --timeout 90s`

**Comment by dat-cao-tien** [comment]
Thank you for your recommendation, I am now able to install CAPI Operator. I installed the `v0.10.0` unintentionally which is the reason it did not work. But I still have to install cert-manager separately

**Comment by henrypham67** [comment]
Thank you for your recommendation, I am now able to install CAPI Operator. I installed the `v0.10.0` unintentionally which is the reason it did not work. But I still have to install cert-manager separately
