### ISSUE TITLE
Implement airgapped support in CLI

### ISSUE THREAD

**Issue by alexander-demicev** [kubernetes-sigs/cluster-api-operator#526]
The current implementation of the upgrade plan in the clustersctl plugin doesn't include air-gapped support https://github.com/kubernetes-sigs/cluster-api-operator/blob/main/cmd/plugin/cmd/upgrade_plan.go#L449, we should add it soon

**Comment by aniruddha2000** [comment]
Is there any resource to read, if I want to help implement this feature?

questions would be 
- What is an airgapped support?
- how it will help and what is the end goal
