### ISSUE TITLE
Install cert-manager dependencies fail

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-operator#531]
**What steps did you take and what happened:**
Ran this command which should install cert-manager:

```
helm install capi-operator capi-operator/cluster-api-operator --create-namespace -n capi-operator-system \
--set infrastructure="azure" \
--set cert-manager.enabled="true" \
--set cert-manager.installCRDs="true" \
--wait --timeout 90s 
```

and 

```
helm install capi-operator capi-operator/cluster-api-operator --create-namespace -n capi-operator-system \
--set infrastructure="azure: \
--set manager.cert-manager.enabled="true" \
--set manager.cert-manager.installCRDs="true" \
--wait --timeout 90s 
```

and got this error
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "capi-operator-serving-cert" namespace: "capi-operator-system" from "": no matches for kind "Certificate" in version "cert-manager.io/v1"
ensure CRDs are installed first, resource mapping not found for name: "capi-operator-selfsigned-issuer" namespace: "capi-operator-system" from "": no matches for kind "Issuer" in version "cert-manager.io/v1"
ensure CRDs are installed first]
```

**What did you expect to happen:**
It installed cert-manager first.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-operator version: 0.10.1
- Cluster-api version: 1.7.2
- Minikube/KIND version: kind 1.29.2 
- Kubernetes version: (use `kubectl version`): 1.30.0
- OS (e.g. from `/etc/os-release`): WSL Ubuntu 22.04

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]

**Comment by Schnitzel** [comment]
I'm getting the same error with a complete fresh k0s 1.30 cluster. 

a workaround is this (from the [helm install docs](https://cert-manager.io/docs/installation/helm/)):

```kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.crds.yaml```

and then run `helm install` with `--set cert-manager.installCRDs=false`

**Comment by mimmus** [comment]
I'm getting the same error with a complete fresh EKS 1.29 cluster.
As a user, I'd like to have a clean installation procedure, especially following Quickstart guide.

**Comment by dtzar** [comment]
The plan is to remove the option to automatically install cert-manager inline with the helm chart install
https://github.com/kubernetes-sigs/cluster-api-operator/pull/521

Unfortunately, even after doing these changes there are still other issues even with the basic quickstart see #532

**Comment by dtzar** [comment]
Closing, since cert-manager is no longer bundled with the chart
