### ISSUE TITLE
Helm chart install and quickstart scenarios not working

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-operator#532]
**What steps did you take and what happened:**
There are a couple bugs with the main CAPI Operator helm chart and the documentation as of now:
Follow the quickstart to install CAPI Operator: https://cluster-api-operator.sigs.k8s.io/01_user/02_quick-start#installing-cluster-api-operator
Error:
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "capi-operator-serving-cert" namespace: "capi-operator-system" from "": no matches for kind "Certificate" in version "cert-manager.io/v1"
ensure CRDs are installed first, resource mapping not found for name: "capi-operator-selfsigned-issuer" namespace: "capi-operator-system" from "": no matches for kind "Issuer" in version "cert-manager.io/v1"
ensure CRDs are installed first]
```
<br>

Running the following command with cert manager installed separately:
```
helm install capi-operator capi-operator/cluster-api-operator --create-namespace -n capi-operator-system --set infrastructure="azure:v1.15.0" --set core="cluster-api:v1.7.2" --set manager.cert-manager.enabled="false" --set manager.cert-manager.installCRDs="false"
```
Error:
```
Error: INSTALLATION FAILED: template: cluster-api-operator/templates/infra.yaml:49:15: executing "cluster-api-operator/templates/infra.yaml" at <$.Values.manager.featureGates>: wrong type for value; expected map[string]interface {}; got interface {}
```
<br>

When installing the chart with manager.featureGates specified like [so](https://github.com/mboersma/cluster-api-charts?tab=readme-ov-file#azure) or with only infrastructure and core specified:
```
helm install capi-operator capi-operator/cluster-api-operator --create-namespace -n capi-operator-system --set infrastructure="azure:v1.15.0" --set core="cluster-api:v1.7.2"
```
Error:
```
Error: INSTALLATION FAILED: failed post-install: warning: Hook post-install cluster-api-operator/templates/infra.yaml failed: 1 error occurred:
        * Internal error occurred: failed calling webhook "vinfrastructureprovider.kb.io": failed to call webhook: Post "https://capi-operator-webhook-service.capi-operator-system.svc:443/mutate-operator-cluster-x-k8s-io-v1alpha2-infrastructureprovider?timeout=10s": dial tcp 10.96.160.166:443: connect: connection refused
```
<br>

**What did you expect to happen:**
The helm chart installs successfully.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-operator version: 0.10.0
- Cluster-api version: v1.7.1
- Minikube/KIND version: v0.22.0
- Kubernetes version: (use `kubectl version`): v1.29.2
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]

**Comment by willie-yao** [comment]
/assign

Will try and fix some of these issues with the helm chart!

**Comment by willie-yao** [comment]
> Error: INSTALLATION FAILED: failed post-install: warning: Hook post-install cluster-api-operator/templates/infra.yaml failed: 1 error occurred:
        * Internal error occurred: failed calling webhook "vinfrastructureprovider.kb.io": failed to call webhook: Post "https://capi-operator-webhook-service.capi-operator-system.svc:443/mutate-operator-cluster-x-k8s-io-v1alpha2-infrastructureprovider?timeout=10s": dial tcp 10.96.160.166:443: connect: connection refused

This error is fixed by using the `--wait` flag on helm install. It seems like this could be easily missed so we should probably add a warning to the docs that this helm chart will not work without `--wait`.

**Comment by dtzar** [comment]
Related to #406
