### ISSUE TITLE
pull-cluster-api-operator-e2e-main needs to be migrated to the community cluster ASAP

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api-operator#567]
if not, the job will be disabled starting August 1st

**Comment by furkatgofurov7** [comment]
Possible fix: https://github.com/kubernetes/test-infra/pull/33091

**Comment by furkatgofurov7** [comment]
Closing it, tests are now moved to new prow cluster and passing in both main and release-0.11 branches.

/close
