### ISSUE TITLE
`--metrics-bind-addr` has been removed from manager

### ISSUE THREAD

**Issue by dhess** [kubernetes-sigs/cluster-api-operator#664]
**What steps did you take and what happened:**

We just updated our Helm chart to `0.15.0`, and now `capi-operator-cluster-api-operator` fails to start with an `unknown flag: --metrics-bind-addr` message.

**Anything else you would like to add:**

Upstream has removed this flag:

https://github.com/kubernetes-sigs/cluster-api/pull/11140

/kind bug

**Comment by furkatgofurov7** [comment]
Thanks for reporting this, we will cut a patch release once the [fix](#665) is merged.

**Comment by dhess** [comment]
Thanks! I see the fix has been merged; can we get a new release?
